### ISSUE TITLE
Player clipping start/end of tracks

### ISSUE THREAD

**Issue by JDen78** [tomahawk-player/tomahawk#452]
Hi,

i'm really happy with Tomahawk as the scan library / update feature  is perfect for someone with v little time, but i'm having a niggling problem with the player clipping a little from the either/both the start/end of tracks. This doesn't happen in other players and I can't see anything in the player preferences that could be causing it to happen

**Comment by muesli** [comment]
Which platform are you running Tomahawk on?

**Comment by dschmidt** [comment]
Also which version?

**Comment by JDen78** [comment]
OSX El Capitan 10.11.1

**Comment by dschmidt** [comment]
I mean, which version of Tomahawk. 0.8.4 or nightly builds? If not on nightly builds, try those maybe

**Comment by JDen78** [comment]
0.8.4, have tried the latest nightly builds but still have the same same problem along with other scanning issues

**Comment by muesli** [comment]
Any particular file type you experience this with?

**Comment by pXlor** [comment]
Hi, I don't know if that's the same issue but I often have Tomahawk clipping the end of tracks, playing from Google Music (I don't have local files). I'm on Ubuntu 14.04 x64, Tomahawk 0.8.4. And for me it can be quite a big part of the track.

**Comment by dschmidt** [comment]
These issues might or might not be fixed on master already, would really help to know

**Comment by pXlor** [comment]
Ok, I could test it but I'm still learning with compilation, I know how to pull the source code from master, could you tell me how to compile it and install it for Ubuntu 14.04 x64 ?

**Comment by dschmidt** [comment]
Yep, sure. I'm on mobile right now, can you find the ubuntu build instructions in our wiki yourself? You can also come to our irc channel/chatroom (see our chat widget on our website) and ask for help there. If you mention muesli or my name (dommex) youll certainly get responses quickly

**Comment by pXlor** [comment]
I should have checked the wiki before, thanks. I'll do that asap and let you know how it goes (it might take me a day or 2 before I find the time to do it).

**Comment by theli-ua** [comment]
This also happens to me as well

**Comment by theli-ua** [comment]
this is also a problem on android btw. This is technically a vlc issue, not sure if there is any workaround we could use

**Comment by theli-ua** [comment]
quoting what I said in the duplicate issue"

wrt "clearly a VLC issue"
I just tested same url that is cut off at the start/end in Tomahawk: it works perfectly fine in VLC itself (using the same libvlc tomahawk is compiled against)

**Comment by theli-ua** [comment]
Played with this again ... It actually does happen with VLC itself as well :-/ , it just didn't happen as often that in tomahawk for w/e reason.

So I guess it could be closed with "upstream" label ... but honestly imo this be better fixed by tomahawk itself ( moving to different playback engine for example )

In Tomahawk heres relevant log portion:
[00007f974c4deac8] core input debug: Decoder wait done in 23 ms
[00007f974d4c3038] core audio output warning: playback way too early (-780515): playing silence
[00007f974d4c3038] core audio output debug: inserting 34420 zeroes
[00007f974d4c3038] core audio output warning: playback too late (98581): up-sampling
[00007f974d4c3038] core audio output warning: playback way too late (235966): flushing buffers
[00007f974d4c3038] core audio output debug: inserting 52664 zeroes
[00007f974d4c3038] core audio output warning: playback too late (71082): up-sampling
[00007f974d4c3038] core audio output warning: timing screwed (drift: 142461 us): stopping resampling
[00007f974d4c3038] core audio output warning: playback too late (142808): up-sampling
[00007f974d4c3038] core audio output warning: playback way too late (189793): flushing buffers
[00007f974d4c3038] core audio output debug: inserting 52484 zeroes

**Comment by theli-ua** [comment]
I just added an ability to specify additional arguments to vlc engine in advanced settings.
Could anyone affected try and download nightly, open preferences, go to advanced and put
--network-caching=10000
into vlc additional arguments.
And test after restart.

**Comment by theli-ua** [comment]
closing this, reopen if the above does not help you on nightly/master
